# Generated by Django 2.0.1 on 2018-03-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20180215_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_js',
            field=models.TextField(blank=True, help_text="Printed just before the closing </head> tag. Make sure it's an async script. It will be rendered as-is, unescaped, so make sure its coming from a trusted source.", null=True, verbose_name='Custom JS'),
        ),
    ]
