# Generated by Django 2.0.1 on 2018-03-19 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_squashed_0078_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='buttoninmodule',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttoninmodules', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='imageingallery',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageingallerys', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='language',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listitems', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='page',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='style',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='events.Event'),
        ),
    ]
