# Generated by Django 2.0.1 on 2018-03-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180319_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='buttons_justify',
            field=models.CharField(choices=[('LEFT', '⯇ Left'), ('CENTER', '￭ Center'), ('RIGHT', '⯈ Right')], default='CENTER', max_length=6, verbose_name='Buttons Align'),
        ),
    ]
